import pandas as pd
my_df = pd.read_csv("my_df.csv")
서울 = pd.read_csv("서울.csv")
울산 = pd.read_csv("울산.csv")
광주 = pd.read_csv("광주.csv")
대구 = pd.read_csv("대구.csv")
부산 = pd.read_csv("부산.csv")
대전 = pd.read_csv("대전.csv")
인천 = pd.read_csv("인천.csv")
전남 = pd.read_csv("전남.csv")
전북 = pd.read_csv("전북.csv")
경남 = pd.read_csv("경남.csv")
강원 = pd.read_csv("강원.csv")
경기 = pd.read_csv("경기.csv")
제주 = pd.read_csv("제주.csv")
세종 = pd.read_csv("세종.csv")
충남 = pd.read_csv("충남.csv")