import pandas as pd
my_df = pd.read_csv("database\my_df.csv")
서울 = pd.read_csv("database\서울.csv")
울산 = pd.read_csv("database\울산.csv")
광주 = pd.read_csv("database\광주.csv")
대구 = pd.read_csv("database\대구.csv")
부산 = pd.read_csv("database\부산.csv")
대전 = pd.read_csv("database\대전.csv")
인천 = pd.read_csv("database\인천.csv")
전남 = pd.read_csv("database\전남.csv")
전북 = pd.read_csv("database\전북.csv")
경남 = pd.read_csv("database\경남.csv")
강원 = pd.read_csv("database\강원.csv")
경기 = pd.read_csv("database\경기.csv")
제주 = pd.read_csv("database\제주.csv")
세종 = pd.read_csv("database\세종.csv")
충남 = pd.read_csv("database\충남.csv")